# Generated by Django 3.1.7 on 2021-04-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_auto_20210408_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активен'),
        ),
    ]
