# Generated by Django 2.2.19 on 2021-03-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagesapp", "0002_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productcategory",
            old_name="decription",
            new_name="description",
        ),
    ]
