# Generated by Django 2.2.19 on 2021-03-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagesapp", "0003_auto_20210302_1720"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=50, verbose_name="номер телефона"),
                ),
                (
                    "email",
                    models.EmailField(max_length=150, verbose_name="электронная почта"),
                ),
                (
                    "city",
                    models.CharField(default="Москва", max_length=120, verbose_name="город"),
                ),
                (
                    "address",
                    models.CharField(max_length=254, verbose_name="адресс"),
                ),
            ],
        ),
    ]
