# Generated by Django 2.2.19 on 2021-03-03 12:11

from django.db import migrations


def forwards_func(apps, schema_editor):
    pro_cat_model = apps.get_model("pagesapp", "ProductCategory")
    pro_model = apps.get_model("pagesapp", "Product")
    con_model = apps.get_model("pagesapp", "Contact")

    pro_cat_obj = pro_cat_model.objects.create(pk=1, name="дом", description="Мебель для домашнего интерьера")

    pro_model.objects.create(
        pk=1,
        category=pro_cat_obj,
        name="комфорт 1",
        image="products_images/product-1.jpg",
        short_desc="комфортный стул",
        description="подойдет для просмотра фильмов",
        price=3299,
        quantity=17,
    )
    pro_model.objects.create(
        pk=2,
        category=pro_cat_obj,
        name="комфорт 2",
        image="products_images/product-2.jpg",
        short_desc="комфортный стул",
        description="подойдет для просмотра фильмов",
        price=4500,
        quantity=10,
    )
    del pro_cat_obj

    pro_cat_obj = pro_cat_model.objects.create(pk=2, name="офис", description="Мебель для офиса")
    pro_model.objects.create(
        pk=3,
        category=pro_cat_obj,
        name="комфорт 3",
        image="products_images/product-3.jpg",
        short_desc="комфортный стул",
        description="подойдет для просмотра фильмов",
        price=500,
        quantity=31,
    )
    pro_model.objects.create(
        pk=4,
        category=pro_cat_obj,
        name="комфорт 4",
        image="products_images/product-4.jpg",
        short_desc="комфортный стул",
        description="подойдет для просмотра фильмов",
        price=2290,
        quantity=18,
    )
    del pro_cat_obj

    pro_cat_obj = pro_cat_model.objects.create(pk=3, name="модерн", description='Мебель в стиле "Модерн"')
    pro_model.objects.create(
        pk=5,
        category=pro_cat_obj,
        name="комфорт 5",
        image="products_images/product-5-sm.jpg",
        short_desc="комфортный стул",
        description="подойдет для просмотра фильмов",
        price=9699,
        quantity=7,
    )
    pro_model.objects.create(
        pk=6,
        category=pro_cat_obj,
        name="комфорт 6",
        image="products_images/product-6.jpg",
        short_desc="комфортный стул",
        description="подойдет для просмотра фильмов",
        price=5499,
        quantity=27,
    )
    del pro_cat_obj

    pro_cat_obj = pro_cat_model.objects.create(
        pk=4,
        name="классика",
        description="Классическая мебель",
    )
    pro_model.objects.create(
        pk=7,
        category=pro_cat_obj,
        name="комфорт 7",
        image="products_images/product-7.jpg",
        short_desc="комфортный стул",
        description="подойдет для просмотра фильмов",
        price=499,
        quantity=63,
    )
    pro_model.objects.create(
        pk=8,
        category=pro_cat_obj,
        name="комфорт 8",
        image="products_images/product-8.jpg",
        short_desc="комфортный стул",
        description="подойдет для просмотра фильмов",
        price=1499,
        quantity=46,
    )
    del pro_cat_obj

    pro_cat_obj = pro_cat_model.objects.create(
        pk=5,
        name="бизнес",
        description="Мебель бизнес класса",
    )
    pro_model.objects.create(
        pk=9,
        category=pro_cat_obj,
        name="комфорт 9",
        image="products_images/product-9.jpg",
        short_desc="комфортный стул",
        description="подойдет для просмотра фильмов",
        price=4390,
        quantity=38,
    )
    pro_model.objects.create(
        pk=10,
        category=pro_cat_obj,
        name="комфорт 10",
        image="products_images/product-10.jpg",
        short_desc="комфортный стул",
        description="подойдет для просмотра фильмов",
        price=10599,
        quantity=8,
    )
    del pro_cat_obj

    con_model.objects.create(
        pk=1,
        phone="777-77-77",
        email="info@mail.ru",
        city="Москва",
        address="В пределах МКАД",
    )
    con_model.objects.create(
        pk=2,
        phone="766-66-66",
        email="infoPr@mail.ru",
        city="Петербург",
        address="Васильевский остров",
    )
    con_model.objects.create(
        pk=3,
        phone="755-55-55",
        email="infoTr@mail.ru",
        city="Тверь",
        address="Садовая 22/1",
    )


def revers_func(apps, schema_editor):
    pro_cat_model = apps.get_model("pagesapp", "ProductCategory")
    con_model = apps.get_model("pagesapp", "Contact")

    pro_cat_model.objects.all().delete()
    con_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("pagesapp", "0004_contact"),
    ]

    operations = [migrations.RunPython(forwards_func, revers_func)]
