# Generated by Django 2.2.19 on 2021-03-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pagesapp", "0005_fill_db")]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="категория активна"),
        )
    ]
