# Generated by Django 2.2.12 on 2021-04-01 17:26

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0005_auto_20210401_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 17, 26, 45, 51570, tzinfo=utc)),
        ),
    ]
