# Generated by Django 3.1.7 on 2021-04-08 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0010_auto_20210408_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 15, 53, 20, 704903, tzinfo=utc)),
        ),
    ]
