# Generated by Django 3.1.7 on 2021-04-14 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0011_auto_20210408_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 14, 23, 8, 10915, tzinfo=utc)),
        ),
    ]
