# Generated by Django 3.1.7 on 2021-04-15 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0012_auto_20210414_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 14, 32, 36, 196089, tzinfo=utc)),
        ),
    ]
