# Generated by Django 3.1.7 on 2021-04-22 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0013_auto_20210415_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 14, 4, 16, 838373, tzinfo=utc)),
        ),
    ]
